### ISSUE TITLE
After updating to 0.2.2 Keystone does not start

### ISSUE THREAD

**Issue by auwtch** [keystonejs/keystone-classic#159]
Before the upgrade everything was fine.
After, I see this:

---

 Salts 

 Salts 

$2a$08$VowU8I4XkX3ZeArHqUAzHu
$2a$10$AbV6j/DZMB/LbxvUUU8ij.

 Hashes 

$2a$08$VowU8I4XkX3ZeArHqUAzHudiZtOv08O9JpM0aFkop30MlEoj6oZ12
$2a$08$VowU8I4XkX3ZeArHqUAzHudiZtOv08O9JpM0aFkop30MlEoj6oZ12
$2a$08$VowU8I4XkX3ZeArHqUAzHuQZ7/TNqI6LvZdzrOjvMDSzQLxsw9PoK
$2a$08$VowU8I4XkX3ZeArHqUAzHuQZ7/TNqI6LvZdzrOjvMDSzQLxsw9PoK
$2a$10$AbV6j/DZMB/LbxvUUU8ij.t6rJp9lpr7cRA9yQIJXyDOaVSEGc8Wu
$2a$10$AbV6j/DZMB/LbxvUUU8ij.t6rJp9lpr7cRA9yQIJXyDOaVSEGc8Wu
$2a$10$AbV6j/DZMB/LbxvUUU8ij.wgCzbKJLussgotaa40nlDGvuQzPWq9y
$2a$10$AbV6j/DZMB/LbxvUUU8ij.wgCzbKJLussgotaa40nlDGvuQzPWq9y
$2a$10$L12ubdZZETSulfTb59xYAu3zv6LvX4/WMYDqUl9nUm1CxGeXNlnDC
$2a$10$yJ5Y95X8obYq7d077Lu7xOEhtgvwL/rHRmflK9t27d4uTY/wnynDm

 First Set of Compares 

PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED

 Second Set of Compares 

PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED

 -------------------- UTF-8 passwords --------------------

 Hashes 

$2a$05$000000000000000000000uaBuzMifgawd3t0WyKm/uX.nt7g6AJji
$2a$05$000000000000000000000uaBuzMifgawd3t0WyKm/uX.nt7g6AJji
$2a$05$000000000000000000000uzGxBCdJU9zsB/SFFJ5k8a9yNpbD91Tm
$2a$05$000000000000000000000uzGxBCdJU9zsB/SFFJ5k8a9yNpbD91Tm

 Third Set of Compares 

PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
PASSED
coffee> Error: Cannot find module 'jison'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/.../node_modules/keystone/node_modules/cloudinary/node_modules/coffee-script/lib/coffee-script/grammar.js:5:12)
    at Object.<anonymous> (/.../node_modules/keystone/node_modules/cloudinary/node_modules/coffee-script/lib/coffee-script/grammar.js:606:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
$2a$08$H7Y8bKXmkH449ErsPdxPWu
$2a$10$mhHe8qe8WEGp.aNyvnACvu

 Hashes 

$2a$08$H7Y8bKXmkH449ErsPdxPWuGsPhVUVjF9Uzhwd7u2vv5NGkPZdn6N.
$2a$08$H7Y8bKXmkH449ErsPdxPWuGsPhVUVjF9Uzhwd7u2vv5NGkPZdn6N.
$2a$10$mhHe8qe8WEGp.aNyvnACvuxvQFuc2dugSjzO541cNFB.FBCoGQcje
$2a$10$mhHe8qe8WEGp.aNyvnACvuxvQFuc2dugSjzO541cNFB.FBCoGQcje

 True Compares 

true
true
true
true

 False Compares 

false
false
false
false

---

All, nothing else happens
